# Generated by Django 5.1.4 on 2024-12-07 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('image', models.FileField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('code_type', models.CharField(default='manufacturer', max_length=40)),
                ('gear_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.gear')),
            ],
        ),
        migrations.CreateModel(
            name='GearCategories',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('gear_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.gear')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=4)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleGear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=120)),
                ('gear_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.gear')),
                ('vehicle_uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.vehicle')),
            ],
            options={
                'unique_together': {('gear_uuid', 'vehicle_uuid')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gear_uuid',
            field=models.ManyToManyField(through='market.VehicleGear', to='market.gear'),
        ),
    ]
